In [2]:
import geopandas as gpd
import pandas as pd
import numpy as np

In [6]:
districts = gpd.read_file("../../../poppy/data/district398/")
districts.head()

,OBJECTID,PROV_34_NA,DIST_34_NA,DISTID,PROVID,geometry
0,1,Hirat,Gulran,2007,20,"POLYGON ((61.13156 35.11849, 61.13137 35.11949..."
1,2,Hirat,Koshk,2006,20,"POLYGON ((62.00758 35.44605, 62.02049 35.44333..."
2,3,Hirat,Koshki Kohna,2016,20,"POLYGON ((62.47754 35.27873, 62.47791 35.27881..."
3,4,Hirat,Kohsan,2008,20,"POLYGON ((61.60531 34.88130, 61.60174 34.87717..."
4,5,Hirat,Ghoryan,2009,20,"POLYGON ((61.75743 34.65122, 61.75567 34.64950..."

In [7]:
districts[districts['PROV_34_NA']=='Kandahar']

,OBJECTID,PROV_34_NA,DIST_34_NA,DISTID,PROVID,geometry
40,41,Kandahar,Registan,2409,24,"POLYGON ((64.67715 30.74035, 64.67779 30.74041..."
41,42,Kandahar,Shorabak,2410,24,"POLYGON ((65.82122 30.59914, 65.82616 30.59914..."
42,43,Kandahar,Spin Boldak,2411,24,"POLYGON ((65.82117 30.59930, 65.82055 30.60128..."
43,44,Kandahar,Arghistan,2412,24,"POLYGON ((66.08038 31.37709, 66.08044 31.37726..."
44,45,Kandahar,Panjwayi,2408,24,"POLYGON ((64.72872 31.26891, 64.73559 31.26911..."
45,46,Kandahar,Kandahar,2401,24,"POLYGON ((65.57705 31.60206, 65.57729 31.60304..."
46,47,Kandahar,Daman,2402,24,"POLYGON ((65.73998 31.63110, 65.73952 31.64108..."
47,48,Kandahar,Shah Wali Kot,2403,24,"POLYGON ((65.80308 31.72837, 65.80184 31.73022..."
48,49,Kandahar,Arghandab,2404,24,"POLYGON ((65.54479 31.61699, 65.54362 31.61699..."
49,50,Kandahar,Maywand,2407,24,"POLYGON ((64.90818 31.92599, 64.90831 31.92347..."
50,51,Kandahar,Ghorak,2406,24,"POLYGON ((65.23584 32.32100, 65.23642 32.32113..."
51,52,Kandahar,Zhari,2416,24,"POLYGON ((65.32869 31.74355, 65.32891 31.74353..."
52,53,Kandahar,Khakrez,2405,24,"POLYGON ((65.43139 32.27510, 65.43162 32.27523..."
58,59,Kandahar,Nesh,2415,24,"POLYGON ((65.63315 32.56959, 65.63585 32.56924..."
111,113,Kandahar,Miya Nishin,2414,24,"POLYGON ((66.15838 32.44557, 66.15829 32.44591..."
397,400,Kandahar,Maruf,2413,24,"POLYGON ((67.58138 31.50726, 67.58161 31.50703..."